UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000724' ) WHERE [EndPointAssessorUkprn] = 10022712;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '292786') WHERE [EndPointAssessorUkprn] = 10022712;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '2849598' ) WHERE [EndPointAssessorUkprn] = 10029857;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '969051' ) WHERE [EndPointAssessorUkprn] = 90000315;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '4190816' ) WHERE [EndPointAssessorUkprn] = 10025729;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000877' ) WHERE [EndPointAssessorUkprn] = 10055891;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000727' ) WHERE [EndPointAssessorUkprn] = 10001328;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '244067') WHERE [EndPointAssessorUkprn] = 10001328;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000850' ) WHERE [EndPointAssessorUkprn] = 10038999;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000117' ) WHERE [EndPointAssessorUkprn] = 10009931;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '312832') WHERE [EndPointAssessorUkprn] = 10009931;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3812163' ) WHERE [EndPointAssessorUkprn] = 10009688;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '2700780' ) WHERE [EndPointAssessorUkprn] = 10022677;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5508318' ) WHERE [EndPointAssessorUkprn] = 10022682;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '2962694' ) WHERE [EndPointAssessorUkprn] = 10020431;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3829217' ) WHERE [EndPointAssessorUkprn] = 10022697;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1079785') WHERE [EndPointAssessorUkprn] = 10022697;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '872828' ) WHERE [EndPointAssessorUkprn] = 10022490;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000487' ) WHERE [EndPointAssessorUkprn] = 10014111;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '1262100' ) WHERE [EndPointAssessorUkprn] = 10022717;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '2380675' ) WHERE [EndPointAssessorUkprn] = 10006987;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '701770') WHERE [EndPointAssessorUkprn] = 10006987;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000647' ) WHERE [EndPointAssessorUkprn] = 10007785;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7212507' ) WHERE [EndPointAssessorUkprn] = 10030507;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '225180' ) WHERE [EndPointAssessorUkprn] = 10022714;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '2881056' ) WHERE [EndPointAssessorUkprn] = 10002809;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000876' ) WHERE [EndPointAssessorUkprn] = 10001331;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1017938') WHERE [EndPointAssessorUkprn] = 10001331;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000778' ) WHERE [EndPointAssessorUkprn] = 10001333;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1091035') WHERE [EndPointAssessorUkprn] = 10001333;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1068863') WHERE [EndPointAssessorUkprn] = 10054568;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '9396974' ) WHERE [EndPointAssessorUkprn] = 10049534;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000653' ) WHERE [EndPointAssessorUkprn] = 10007792;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '1518983' ) WHERE [EndPointAssessorUkprn] = 10022663;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1050724') WHERE [EndPointAssessorUkprn] = 10022663;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '4752100' ) WHERE [EndPointAssessorUkprn] = 10043865;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '2896700' ) WHERE [EndPointAssessorUkprn] = 10009696;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1034808') WHERE [EndPointAssessorUkprn] = 10009696;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '6504179' ) WHERE [EndPointAssessorUkprn] = 10022405;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3007236' ) WHERE [EndPointAssessorUkprn] = 10054451;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7464445' ) WHERE [EndPointAssessorUkprn] = 10036649;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000732' ) WHERE [EndPointAssessorUkprn] = 10010201;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '4068966' ) WHERE [EndPointAssessorUkprn] = 10036631;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3803848' ) WHERE [EndPointAssessorUkprn] = 10024089;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '6478925' ) WHERE [EndPointAssessorUkprn] = 10030505;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5606069' ) WHERE [EndPointAssessorUkprn] = 10020932;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7545603' ) WHERE [EndPointAssessorUkprn] = 10052758;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7196797' ) WHERE [EndPointAssessorUkprn] = 10045166;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'SC371435' ) WHERE [EndPointAssessorUkprn] = 10058072;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3859442' ) WHERE [EndPointAssessorUkprn] = 10007089;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000246' ) WHERE [EndPointAssessorUkprn] = 10023923;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '6423637' ) WHERE [EndPointAssessorUkprn] = 10026575;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '4813840' ) WHERE [EndPointAssessorUkprn] = 10022661;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '6904840' ) WHERE [EndPointAssessorUkprn] = 10030276;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000263' ) WHERE [EndPointAssessorUkprn] = 10012815;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '211014') WHERE [EndPointAssessorUkprn] = 10012815;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5423260' ) WHERE [EndPointAssessorUkprn] = 10024320;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5327136' ) WHERE [EndPointAssessorUkprn] = 10022681;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '6559484' ) WHERE [EndPointAssessorUkprn] = 10030009;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5371364' ) WHERE [EndPointAssessorUkprn] = 90000354;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '1103638' ) WHERE [EndPointAssessorUkprn] = 10046538;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7827508' ) WHERE [EndPointAssessorUkprn] = 10043783;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '1154751' ) WHERE [EndPointAssessorUkprn] = 10061404;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1154751') WHERE [EndPointAssessorUkprn] = 10061404;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5038056' ) WHERE [EndPointAssessorUkprn] = 10032760;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1103300') WHERE [EndPointAssessorUkprn] = 10032760;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3274864' ) WHERE [EndPointAssessorUkprn] = 90000560;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '8842626' ) WHERE [EndPointAssessorUkprn] = 10047301;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '2050044' ) WHERE [EndPointAssessorUkprn] = 10022592;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '295192') WHERE [EndPointAssessorUkprn] = 10022592;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '2418331' ) WHERE [EndPointAssessorUkprn] = 90000591;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3841918' ) WHERE [EndPointAssessorUkprn] = 10004193;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '8003851' ) WHERE [EndPointAssessorUkprn] = 10036952;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3567982' ) WHERE [EndPointAssessorUkprn] = 10022695;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5895742' ) WHERE [EndPointAssessorUkprn] = 10038829;

UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '9079735' ) WHERE [EndPointAssessorUkprn] = 10049123;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7066687' ) WHERE [EndPointAssessorUkprn] = 10036355;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1144894') WHERE [EndPointAssessorUkprn] = 10036355;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000262' ) WHERE [EndPointAssessorUkprn] = 10020595;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '210252') WHERE [EndPointAssessorUkprn] = 10020595;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '6926458' ) WHERE [EndPointAssessorUkprn] = 10039259;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '4910891' ) WHERE [EndPointAssessorUkprn] = 10030670;

UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '2865522' ) WHERE [EndPointAssessorUkprn] = 10001186;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3077957' ) WHERE [EndPointAssessorUkprn] = 10044321;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '6033238' ) WHERE [EndPointAssessorUkprn] = 10007842;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7392472' ) WHERE [EndPointAssessorUkprn] = 10048380;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3323774' ) WHERE [EndPointAssessorUkprn] = 10032878;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '4117784' ) WHERE [EndPointAssessorUkprn] = 10022660;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1086947') WHERE [EndPointAssessorUkprn] = 10022660;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '4740553' ) WHERE [EndPointAssessorUkprn] = 10007137;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '2638349' ) WHERE [EndPointAssessorUkprn] = 10022671;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '1461331' ) WHERE [EndPointAssessorUkprn] = 10029117;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000658' ) WHERE [EndPointAssessorUkprn] = 10007795;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '4429302' ) WHERE [EndPointAssessorUkprn] = 10057402;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '850083' ) WHERE [EndPointAssessorUkprn] = 10030859;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '391886' ) WHERE [EndPointAssessorUkprn] = 10026420;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '269275') WHERE [EndPointAssessorUkprn] = 10022702;

UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '10923816' ) WHERE [EndPointAssessorUkprn] = 90000333;

UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '20194' ) WHERE [EndPointAssessorUkprn] = 10006397;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '9484306' ) WHERE [EndPointAssessorUkprn] = 10057353;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '10070090' ) WHERE [EndPointAssessorUkprn] = 10063519;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000758' ) WHERE [EndPointAssessorUkprn] = 10009191;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1079797') WHERE [EndPointAssessorUkprn] = 10009191;

UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7673903' ) WHERE [EndPointAssessorUkprn] = 10058914;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '6228587' ) WHERE [EndPointAssessorUkprn] = 10055126;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '4005034' ) WHERE [EndPointAssessorUkprn] = 10008562;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1081749') WHERE [EndPointAssessorUkprn] = 10008562;

UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '8813670' ) WHERE [EndPointAssessorUkprn] = 10053076;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '6193387' ) WHERE [EndPointAssessorUkprn] = 10034416;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '9305101' ) WHERE [EndPointAssessorUkprn] = 10048132;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5467600' ) WHERE [EndPointAssessorUkprn] = 10046623;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '974438' ) WHERE [EndPointAssessorUkprn] = 10004048;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5493384' ) WHERE [EndPointAssessorUkprn] = 10007832;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1110346') WHERE [EndPointAssessorUkprn] = 10007832;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '1695822' ) WHERE [EndPointAssessorUkprn] = 10026268;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7687474' ) WHERE [EndPointAssessorUkprn] = 10055240;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5161359' ) WHERE [EndPointAssessorUkprn] = 10007776;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7652902' ) WHERE [EndPointAssessorUkprn] = 10054050;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '6023243' ) WHERE [EndPointAssessorUkprn] = 10007145;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '119249' ) WHERE [EndPointAssessorUkprn] = 10008155;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '213121') WHERE [EndPointAssessorUkprn] = 10008155;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '10611566' ) WHERE [EndPointAssessorUkprn] = 10063588;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3079282' ) WHERE [EndPointAssessorUkprn] = 10007851;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000251' ) WHERE [EndPointAssessorUkprn] = 10020663;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1151468') WHERE [EndPointAssessorUkprn] = 10043119;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7321875' ) WHERE [EndPointAssessorUkprn] = 10044364;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7819598' ) WHERE [EndPointAssessorUkprn] = 10065965;

UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7485685' ) WHERE [EndPointAssessorUkprn] = 10035578;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '2476398' ) WHERE [EndPointAssessorUkprn] = 10066241;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3895053' ) WHERE [EndPointAssessorUkprn] = 10008044;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7901202' ) WHERE [EndPointAssessorUkprn] = 10055970;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7891810' ) WHERE [EndPointAssessorUkprn] = 10036142;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '10895629' ) WHERE [EndPointAssessorUkprn] = 10065386;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '10781926' ) WHERE [EndPointAssessorUkprn] = 10065613;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7803789' ) WHERE [EndPointAssessorUkprn] = 10059355;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '6803736' ) WHERE [EndPointAssessorUkprn] = 10026397;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7613918' ) WHERE [EndPointAssessorUkprn] = 10035774;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5075197' ) WHERE [EndPointAssessorUkprn] = 10066155;

UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '7475259' ) WHERE [EndPointAssessorUkprn] = 10067506;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3548155' ) WHERE [EndPointAssessorUkprn] = 10055832;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '6840793' ) WHERE [EndPointAssessorUkprn] = 10034146;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '986761' ) WHERE [EndPointAssessorUkprn] = 10004078;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '10236797' ) WHERE [EndPointAssessorUkprn] = 10057399;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000247' ) WHERE [EndPointAssessorUkprn] = 10020611;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '4801169' ) WHERE [EndPointAssessorUkprn] = 10007292;

UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000645' ) WHERE [EndPointAssessorUkprn] = 10006840;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000101' ) WHERE [EndPointAssessorUkprn] = 10020639;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '231060') WHERE [EndPointAssessorUkprn] = 10020639;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5384487' ) WHERE [EndPointAssessorUkprn] = 10036558;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1113542') WHERE [EndPointAssessorUkprn] = 10036558;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', 'RC000537' ) WHERE [EndPointAssessorUkprn] = 10007858;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '2340767' ) WHERE [EndPointAssessorUkprn] = 10022659;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1132226') WHERE [EndPointAssessorUkprn] = 10047322;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '8903538' ) WHERE [EndPointAssessorUkprn] = 10048409;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1161555') WHERE [EndPointAssessorUkprn] = 10048409;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '8849852' ) WHERE [EndPointAssessorUkprn] = 10065867;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '4339277' ) WHERE [EndPointAssessorUkprn] = 10022683;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '5526192' ) WHERE [EndPointAssessorUkprn] = 10018942;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '10078641' ) WHERE [EndPointAssessorUkprn] = 10056268;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3636328' ) WHERE [EndPointAssessorUkprn] = 10023995;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CharityNumber', '1099911') WHERE [EndPointAssessorUkprn] = 10057360;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '8405084' ) WHERE [EndPointAssessorUkprn] = 10065116;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3964134' ) WHERE [EndPointAssessorUkprn] = 10024346;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '3645473' ) WHERE [EndPointAssessorUkprn] = 10020607;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '11238427' ) WHERE [EndPointAssessorUkprn] = 10067176;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '897907' ) WHERE [EndPointAssessorUkprn] = 10004495;
UPDATE [Organisations] SET [OrganisationData] = JSON_MODIFY([OrganisationData],'$.CompanyNumber', '8467452' ) WHERE [EndPointAssessorUkprn] = 10041486;
