//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.AssessorService.Web.Resources.Views.Certificate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Declaration {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Declaration() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFA.DAS.AssessorService.Web.Resources.Views.Certificate.Declaration", typeof(Declaration).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm and record a grade.
        /// </summary>
        internal static string ContinueButton {
            get {
                return ResourceManager.GetString("ContinueButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaration.
        /// </summary>
        internal static string Heading {
            get {
                return ResourceManager.GetString("Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By recording a grade for this apprentice, you are confirming that:.
        /// </summary>
        internal static string InfoHeader1 {
            get {
                return ResourceManager.GetString("InfoHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By applying for an apprenticeship certificate for a successful grade, you are also confirming that:.
        /// </summary>
        internal static string InfoHeader2 {
            get {
                return ResourceManager.GetString("InfoHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the assessment was independent of both the training provider and employer.
        /// </summary>
        internal static string InfoLine1 {
            get {
                return ResourceManager.GetString("InfoLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the apprentice has met the minimum duration of the apprenticeship.
        /// </summary>
        internal static string InfoLine2 {
            get {
                return ResourceManager.GetString("InfoLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the apprentice has given permission for you to apply for certificate on their behalf.
        /// </summary>
        internal static string InfoLine3 {
            get {
                return ResourceManager.GetString("InfoLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the apprentice has achieved all the requirements of the assessment plan, including the end-point assessment.
        /// </summary>
        internal static string InfoLine4 {
            get {
                return ResourceManager.GetString("InfoLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the apprentice has achieved the English and maths requirements of the apprenticeship programme.
        /// </summary>
        internal static string InfoLine5 {
            get {
                return ResourceManager.GetString("InfoLine5", resourceCulture);
            }
        }
    }
}
