CREATE FUNCTION [dbo].[ApplyConst_ORGANISATION_SEQUENCE_NO]()
RETURNS SMALLINT
WITH SCHEMABINDING
AS
BEGIN
	RETURN 1;
END;
GO

CREATE FUNCTION [dbo].[ApplyConst_FINANCIAL_SEQUENCE_NO]()
RETURNS SMALLINT
WITH SCHEMABINDING
AS
BEGIN
	RETURN 1;
END;
GO

CREATE FUNCTION [dbo].[ApplyConst_STANDARD_SEQUENCE_NO]()
RETURNS SMALLINT
WITH SCHEMABINDING
AS
BEGIN
	RETURN 2;
END;
GO

CREATE FUNCTION [dbo].[ApplyConst_ORGANISATION_WITHDRAWAL_SEQUENCE_NO]()
RETURNS SMALLINT
WITH SCHEMABINDING
AS
BEGIN
	RETURN 3;
END;
GO

CREATE FUNCTION [dbo].[ApplyConst_STANDARD_WITHDRAWAL_SEQUENCE_NO]()
RETURNS SMALLINT
WITH SCHEMABINDING
AS
BEGIN
	RETURN 4;
END;
GO

CREATE FUNCTION [dbo].[ApplyConst_FINANCIAL_SECTION_NO]()
RETURNS SMALLINT
WITH SCHEMABINDING
AS
BEGIN
	RETURN 3;
END;
GO
