//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.AssessorService.Web.Staff.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OrganisationAndContactMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OrganisationAndContactMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFA.DAS.AssessorService.Web.Staff.Resources.OrganisationAndContactMessages", typeof(OrganisationAndContactMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The charity number is already used by another organisation.
        /// </summary>
        internal static string CharityNumberAlreadyUsed {
            get {
                return ResourceManager.GetString("CharityNumberAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charity number is an invalid format.
        /// </summary>
        internal static string CharityNumberNotValid {
            get {
                return ResourceManager.GetString("CharityNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company number is already used by another organisation.
        /// </summary>
        internal static string CompanyNumberAlreadyUsed {
            get {
                return ResourceManager.GetString("CompanyNumberAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company number is an invalid format.
        /// </summary>
        internal static string CompanyNumberNotValid {
            get {
                return ResourceManager.GetString("CompanyNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact name is missing.
        /// </summary>
        internal static string ContactNameIsMissing {
            get {
                return ResourceManager.GetString("ContactNameIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact name is too short.
        /// </summary>
        internal static string ContactNameIsTooShort {
            get {
                return ResourceManager.GetString("ContactNameIsTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is already used by another organisation.
        /// </summary>
        internal static string EmailAlreadyUsed {
            get {
                return ResourceManager.GetString("EmailAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is invalid.
        /// </summary>
        internal static string EmailIsInvalid {
            get {
                return ResourceManager.GetString("EmailIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email is missing.
        /// </summary>
        internal static string EmailIsMissing {
            get {
                return ResourceManager.GetString("EmailIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name is missing.
        /// </summary>
        internal static string NoOrganisationName {
            get {
                return ResourceManager.GetString("NoOrganisationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name already used.
        /// </summary>
        internal static string OrganisationNameAlreadyUsed {
            get {
                return ResourceManager.GetString("OrganisationNameAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation name too short.
        /// </summary>
        internal static string OrganisationNameTooShort {
            get {
                return ResourceManager.GetString("OrganisationNameTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation type not identified.
        /// </summary>
        internal static string OrganisationTypeNotIdentified {
            get {
                return ResourceManager.GetString("OrganisationTypeNotIdentified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard already added to this organisation.
        /// </summary>
        internal static string StandardAlreadyUsed {
            get {
                return ResourceManager.GetString("StandardAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard code is an invalid format.
        /// </summary>
        internal static string StandardInvalid {
            get {
                return ResourceManager.GetString("StandardInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ukprn is already used by another organisation.
        /// </summary>
        internal static string UkprnAlreadyUsed {
            get {
                return ResourceManager.GetString("UkprnAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukprn is an invalid format.
        /// </summary>
        internal static string UkprnIsInvalidFormat {
            get {
                return ResourceManager.GetString("UkprnIsInvalidFormat", resourceCulture);
            }
        }
    }
}
