//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFA.DAS.AssessorService.Web.Staff.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoatpOrganisationValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoatpOrganisationValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFA.DAS.AssessorService.Web.Staff.Resources.RoatpOrganisationValidation", typeof(RoatpOrganisationValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an existing charity number for ‘{0}’.
        /// </summary>
        internal static string CharityNumberDuplicateMatch {
            get {
                return ResourceManager.GetString("CharityNumberDuplicateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid charity registration number.
        /// </summary>
        internal static string CharityNumberFormat {
            get {
                return ResourceManager.GetString("CharityNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a charity registration number using 14 characters or less.
        /// </summary>
        internal static string CharityNumberLength {
            get {
                return ResourceManager.GetString("CharityNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an existing company number for ‘{0}’.
        /// </summary>
        internal static string CompanyNumberDuplicateMatch {
            get {
                return ResourceManager.GetString("CompanyNumberDuplicateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid company number.
        /// </summary>
        internal static string CompanyNumberFormat {
            get {
                return ResourceManager.GetString("CompanyNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a company number using 8 characters.
        /// </summary>
        internal static string CompanyNumberLength {
            get {
                return ResourceManager.GetString("CompanyNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell us what the new training provider is.
        /// </summary>
        internal static string InvalidProviderTypeId {
            get {
                return ResourceManager.GetString("InvalidProviderTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a legal name.
        /// </summary>
        internal static string LegalNameMandatory {
            get {
                return ResourceManager.GetString("LegalNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a legal name using 200 characters or less.
        /// </summary>
        internal static string LegalNameMaxLength {
            get {
                return ResourceManager.GetString("LegalNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a trading name using 200 characters or less.
        /// </summary>
        internal static string TradingNameMaxLength {
            get {
                return ResourceManager.GetString("TradingNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an existing UKPRN for ‘{0}’.
        /// </summary>
        internal static string UKPRNDuplicateMatch {
            get {
                return ResourceManager.GetString("UKPRNDuplicateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid UKPRN.
        /// </summary>
        internal static string UKPRNFormat {
            get {
                return ResourceManager.GetString("UKPRNFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a UKPRN using 8 numbers.
        /// </summary>
        internal static string UKPRNLength {
            get {
                return ResourceManager.GetString("UKPRNLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a UKPRN.
        /// </summary>
        internal static string UKPRNMandatory {
            get {
                return ResourceManager.GetString("UKPRNMandatory", resourceCulture);
            }
        }
    }
}
