CREATE VIEW [dbo].[StandardCertificates] AS
SELECT 
    Id,
    CertificateData,
    ToBePrinted,
    CreatedAt,
    CreatedBy,
    DeletedAt,
    DeletedBy,
    CertificateReference,
    OrganisationId,
    BatchNumber,
    Status,
    UpdatedAt,
    UpdatedBy,
    Uln, 
    StandardCode,
    ProviderUkPrn,
    CertificateReferenceId,
    LearnRefNumber,
    CreateDay,
    IsPrivatelyFunded,
    PrivatelyFundedStatus,
    StandardUId,
    LearnerFamilyName,
    LearnerGivenNames,
    LearnerFullNameNoSpaces,
    FullName,
    ContactOrganisation,
    ProviderName,
    ContactName,
    CourseOption,
    OverallGrade,
    StandardReference,
    StandardName,
    Version,
    StandardLevel,
    AchievementDate,
    LearningStartDate,
    ContactAddLine1,
    ContactAddLine2,
    ContactAddLine3,
    ContactAddLine4,
    ContactPostCode,
    LatestEPAOutcome
FROM [dbo].[Certificates]
WHERE Type = 'Standard';

