version: '3'

services:
  sfa.das.assessorservice.application.api:
    image: sfa.das.assessorservice.application.api
    build:
      context: .
      dockerfile: SFA.DAS.AssessorService.Application.Api/Dockerfile

  sfa.das.assessorservice.web:
    image: sfa.das.assessorservice.web
    build:
      context: .
      dockerfile: SFA.DAS.AssessorService.Web/Dockerfile

